-----------------------------------------------------
--- Creation Date: 22-Apl-2004
--- Last Update : 22-Apl-2004
--- Aouthor : Isaac Raz
--- Company : Traiana Inc
--- Script Target:
---	Update Database schema 1.7 STF 12.1 to  1.7 STF 12.2 on JPMC project
------------------------------------------------------

set echo on
set feedback on
-- spool  ./log1-7-12-2.log

-- begin
-- alter_constraints('disable');
-- end;
-- /

INSERT INTO ARCH_VERSION ( TIMESTAMP, VERSION, DESCRIPTION, LOGFILE, SOLUTION_VERSION )
	VALUES (sysdate , '1.7.12.2::1', 'jpmc 1.7 stf 12 build 2', '/Arch2.0/installationLog/databaseInstall.log', '1.7.12.2::1');

------- VIEWS SECTION ---------------
CREATE OR REPLACE VIEW V_FXPB_REPORT_OPTION_POSITION 
	( GROUP_ID,TRAIANA_ID, MUREX_ID, EXPIRY_DATE, STRIKE,
	  TRADER_ID, PORTFOLIO_ID, AGREEMENT_ID, TRD_TYPE,
	  FUND_ID, CLIENT_ID, EB_ID, PB_ID,
	  COUNTERPARTY_ID, OPTION_TYPE, CONTRACT_TYPE, PRICE,
	  PREMIUM_TYPE_ID, PREMIUM_CCY, RISK_NOTIONAL, BASE_NOTIONAL,
	  BASE_CCY_ID, RISK_CCY_ID, BASE_CCY, RISK_CCY,
	  DIRECTION, INSTRUMENT_ID, DELTA_CCY, DELTA_CCY_ID,
	  DELTA, SPOT_RATE, SPOT_DATE, CCY_PAIR,
	  GAMMA, VEGA, VOLATILITY, RATE_DIRECTION,
	  UNREALIZED_DAILY_PNL, UNREALIZES_MTM, UNREALIZED_M2D, REALIZED_DAILY_PNL,
	  REALIZES_MTM, REALIZED_M2D, TOTAL_DAILY_PNL, TOTAL_MTM_PNL,
	  TOTAL_MTD_PNL, FAKE_ROW, CORRECT_CCY_PAIR) AS 
	SELECT
	   TG.ID as GROUP_ID
	   ,TRD.ID as TRAIANA_ID
	   ,TRD.OPTION_BO_TRADE_ID as MUREX_ID
 	   ,TRD.EXPIRY_DATE as EXPIRY_DATE
	   ,TRD.RATE as STRIKE
	   ,TRD.TRADER_ID as TRADER_ID
	   ,TRD.PORTFOLIO_ID as PORTFOLIO_ID
	   ,TRD.AGREEMENT as AGREEMENT_ID
	   --
	   ,(case when ((TRD.ROLE_A = 1000002) OR (TRD.ROLE_B = 1000002)) then (1) else
	    (case when ((TRD.ROLE_A = 1000003) OR (TRD.ROLE_B = 1000003)) then (2) else
		(case when ((TRD.ROLE_A = 1000004) OR (TRD.ROLE_B = 1000004)) then (3) else (0)
		end) end) end) as TRD_TYPE -- Bank = 1, Client = 2, Fund = 3
    	,(case when (TRD.ROLE_A=1000004) then TRD.SIDE_A_ORG_ID else (case when (TRD.ROLE_B=1000004) then TRD.SIDE_B_ORG_ID else (-1) end) end) as FUND_ID
	--
	,(case when (NOE.ROLE_A = 1000003) then (NOE.SIDE_A_ORG_ID) else (NOE.SIDE_B_ORG_ID) end) as CLIENT_ID
	,(case when (NOE.ROLE_A = 1000002) then (NOE.SIDE_A_ORG_ID) else (NOE.SIDE_B_ORG_ID) end) as EB_ID
	,NOE.PB_ID as PB_ID
	--
	,(case when (NOE.ROLE_A=1000002) then NOE.SIDE_A_ORG_ID else NOE.SIDE_B_ORG_ID end) as COUNTERPARTY_ID
	,OTYPE.NAME as OPTION_TYPE
	,CTYPE.NAME as CONTRACT_TYPE
	--
	--,NOE.PREMIUM_AMOUNT as PRICE  <-- CR5922
	,NVL(MDVALEXT.MTM_PRICE, 0) as PRICE
	,NOE.PREMIUM_TYPE as PREMIUM_TYPE_ID
	,INSTR4.NAME as PREMIUM_CCY
	--
	,TRD.QUANTITY as RISK_NOTIONAL
	,TRD.QUANTITY2 as BASE_NOTIONAL
	--
	,NOE.BASE_INSTRUMENT_ID as BASE_CCY_ID --ccy2
	,NOE.SECONDARY_INSTRUMENT_ID as RISK_CCY_ID --ccy1
	,INSTR2.NAME as BASE_CCY
	,INSTR1.NAME as RISK_CCY
	--
	,(case when(NOE.ROLE_A = 1000003) then (case when(NOE.DIRECTION=1) then ('Buy') else ('Sell') end)
	else (case when(NOE.DIRECTION=1) then ('Sell') else ('Buy') end) end) as DIRECTION
		 ,NOE.INSTRUMENT_ID as INSTRUMENT_ID
		 -- FXPB_VAL_MD_OPTION_EXT
		 ,INSTR3.NAME as DELTA_CCY
		 ,NVL(MDVALEXT.GREEKS_CCY_ID,1000140) as DELTA_CCY_ID
		 ,NVL(MDVALEXT.DELTA, 0) as DELTA
		 ,NVL(MDVALEXT.GREEKS_SPOT, 1) as SPOT_RATE
		 ,NVL(MDVALEXT.GREEKS_SPOT_DATE, trunc(SYSDATE)-1) as SPOT_DATE
		 ,NVL(MDVALEXT.CCY_PAIR, 'EURUSD') as CCY_PAIR
		 ,NVL(MDVALEXT.GAMMA, 0) as GAMMA
		 ,NVL(MDVALEXT.VEGA, 0) as VEGA
		 ,NVL(MDVALEXT.VOLATILITY, 0) as VOLATILITY
		 ,NVL(MDVALEXT.IS_BASE_CCY_FIRST, 0) as RATE_DIRECTION
		 -- unrealised
		 ,NVL(MDVALEXT.UNREALIZED_DAILY_PNL, 0) as UNREALIZED_DAILY_PNL
		 ,NVL(MDVALEXT.UNREALIZED_INC_PNL, 0) as UNREALIZES_MTM
		 ,NVL(MDVALEXT.UNREALIZED_MONTH2DAY_PNL, 0) as UNREALIZED_M2D
		 -- realised
		 ,NVL(MDVALEXT.REALIZED_DAILY_PNL, 0) as REALIZED_DAILY_PNL
		 ,NVL(MDVALEXT.REALIZED_INC_PNL, 0) as REALIZES_MTM
		 ,NVL(MDVALEXT.REALIZED_MONTH2DAY_PNL, 0) as REALIZED_M2D
		 -- total
		 ,NVL((MDVALEXT.UNREALIZED_DAILY_PNL + MDVALEXT.REALIZED_DAILY_PNL), 0) as TOTAL_DAILY_PNL
		 ,NVL((MDVALEXT.UNREALIZED_INC_PNL + MDVALEXT.REALIZED_INC_PNL), 0) as TOTAL_MTM_PNL
		 ,NVL(MDVALEXT.MONTH2DAY_TOTAL_PNL, 0) as TOTAL_MTD_PNL
		 ,(case when (MDVALEXT.MUREX_TRADE_ID = NVL(MDVALEXT.MUREX_TRADE_ID, 0)) then (0) else (1) end) as FAKE_ROW
		 ,ABCR.CCY_PAIR as CORRECT_CCY_PAIR
  FROM
	fxpb_option_trade TRD
	,fxpb_option_noe NOE
	,fxpb_md_option_ext MDVALEXT
	,ARCH_CODE_MEMBER OTYPE   -- Option Type
	,ARCH_CODE_MEMBER CTYPE   -- Contract Type
	,A_INSTRUMENT INSTR1
	,A_INSTRUMENT INSTR2
	,A_INSTRUMENT INSTR3
	,A_INSTRUMENT INSTR4
	,FXPB_OPTION_TRADE  TG--TRADE GROUP
	,A_TA_TA_REL RELATION
	,ARCH_BILLING_CCY_PAIR ABCR
 WHERE
    -- joints
	(TG.TYPE = 4009)
	AND	(RELATION.PARENT_TA_ID = TG.ID)
	AND (RELATION.RELATION = 13)
	AND (RELATION.CHILD_TA_ID = TRD.ID)
	AND (TRD.TRADING_ACTIVITY_SIDE_A = NOE.ID)
	--AND (MDVAL.ID = MDVALEXT.ID)  -- BUG joint should be by murex ID
	AND (TRD.OPTION_BO_TRADE_ID = TO_CHAR(MDVALEXT.MUREX_TRADE_ID(+)))
	AND (OTYPE.GROUP_ID = 1100022) AND (OTYPE.CODE_KEY = NOE.OPTION_TYPE)
	AND (CTYPE.GROUP_ID = 3000) AND (CTYPE.CODE_KEY = NOE.CONTRACT_TYPE)
	AND (INSTR2.ID = NOE.BASE_INSTRUMENT_ID)
	AND (INSTR1.ID = NOE.SECONDARY_INSTRUMENT_ID)
	AND (INSTR3.ID = NVL(MDVALEXT.GREEKS_CCY_ID,1000140))
	AND (INSTR4.ID = NOE.PREMIUM_CCY)
	-- Calculate correct CCY pair
	AND (((ABCR.FIRST_CCY_ID = NOE.BASE_INSTRUMENT_ID)AND(ABCR.SECOND_CCY_ID = NOE.SECONDARY_INSTRUMENT_ID))
	 OR ((ABCR.FIRST_CCY_ID = NOE.SECONDARY_INSTRUMENT_ID)AND(ABCR.SECOND_CCY_ID = NOE.BASE_INSTRUMENT_ID)))
	-- trades filtering
	AND (TRD.TYPE = 4008)			 -- filter group trades
	AND ((TRD.ROLE_A = 1000001) OR (TRD.ROLE_B = 1000001)) -- filters master trade
	AND (TRD.LIFE_STATUS IN (2,5))   -- booked (2), not booked (5)
	--AND ((TRD.BOR_STATUS = 2) OR (TRD.OPTION_BO_TRADE_ID IS NULL))         -- reconciled (2)
	AND (TRD.BOR_STATUS = 2)
	-- OPTION_STATUS active <-> (1)
	AND ((TRD.OPTION_STATUS = 1)  OR (TRD.EXPIRY_DATE >= trunc(SYSDATE)-1));



-- begin
-- alter_constraints('enable');
-- end;
-- /

-- spool  off
