delete from ARCH_REPORT_COLUMN where id=1000118;
INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE,
VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME ) VALUES (
1000118, 1000100, 'LIFE_STATUS', 'Life', 'Life', 'String', 'string', NULL, 'VFXPBTradeLifeStatus'
, NULL, 'lifeStatus', 30, 'LIFE_STATUS');