-----------------------------------------------------
--- Creation Date: 15-Apl-2004
--- Last Update : 16-Apl-2004
--- Aouthor : Isaac Raz
--- Company : Traiana Inc
--- Script Target:
---	Update Database schema 1.7 STF 12.1 Build 1 to 1.7 STF 12.1 Build 2 on JPMC project
------------------------------------------------------

begin
alter_constraints('disable');
end;
/

INSERT INTO ARCH_VERSION ( TIMESTAMP, VERSION, DESCRIPTION, LOGFILE, SOLUTION_VERSION )
	VALUES (sysdate , '1.7.12.1::2', 'jpmc 1.7 stf 12 build 2', '/Arch2.0/installationLog/databaseInstall.log', '1.7.12.1::2');

INSERT INTO ARCH_LOG_MESSAGES ( MSG_ID, MESSAGE, LOG_MSG_DEVISION, LANG ) VALUES (
20030, 'Mq Activation process: ERROR while setting Restart Listener Flag to {0} for Address Id {1}', 7, NULL);
INSERT INTO ARCH_LOG_MESSAGES ( MSG_ID, MESSAGE, LOG_MSG_DEVISION, LANG ) VALUES (
20031, 'Mq Activation process: ERROR while initializing MQ Connection. Error Code: {0}, linked exception message: {1}. Setting on the Restart Listener flag for Address Id {2}.', 7, NULL);
INSERT INTO ARCH_LOG_MESSAGES ( MSG_ID, MESSAGE, LOG_MSG_DEVISION, LANG ) VALUES (
20032, 'Mq Activation process: ERROR while getting messages from MQ queue. Error Code: {0}, linked exception message: {1}. Setting Restart Listener flag for Address Id {2}.', 7, NULL);
INSERT INTO ARCH_LOG_MESSAGES ( MSG_ID, MESSAGE, LOG_MSG_DEVISION,
LANG ) VALUES (50003, 'No item was selected for operation: {0}', 23, NULL); 
	



delete A_INSTRUMENT where id BETWEEN 1000111 AND 1000218;
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000111, 5006, 'AED', 'United Arab Emirates, Dirham', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000112, 5006, 'AOR', 'Angola, Kwanza Reajustado', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000113, 5006, 'ARS', 'Argentina, Argentine Peso', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000114, 5006, 'ATS', 'Austria, Schilling', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000115, 5006, 'AUD', 'Australia, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000116, 5006, 'BEF', 'Belgium, Franc', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000117, 5006, 'BGL', 'Bulgaria, Lev', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000118, 5006, 'BHD', 'Bahrain, Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000119, 5006, 'BIF', 'Burundi, Burundi Franc', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000120, 5006, 'BRL', 'Brazil, Brazilian Real', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000121, 5006, 'BWP', 'Botswana, Pula', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000122, 5006, 'BYB', 'Belarus, Belarussian Ruble', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000123, 5006, 'CAD', 'Canada, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000124, 5006, 'CHF', 'Switzerland, Franc', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000125, 5006, 'CLP', 'Chile, Peso', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000126, 5006, 'CNY', 'China, Yuan Renminbi', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000127, 5006, 'COP', 'Colombia, Peso', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000128, 5006, 'CYP', 'Cyprus, Pound', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000129, 5006, 'CZK', 'Czech Republic, Koruna', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000130, 5006, 'DEM', 'Germany, Deutsche Mark', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000131, 5006, 'DJF', 'Djibouti, Franc', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000132, 5006, 'DKK', 'Denmark, Krone', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000133, 5006, 'DZD', 'Algeria, Algerian Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000134, 5006, 'ECS', 'Ecuador, Sucre', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000135, 5006, 'ECU', 'European Currency Unit (XEU)', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000136, 5006, 'EEK', 'Estonia, Kroon', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000137, 5006, 'EGP', 'Egypt, Pound', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000138, 5006, 'ESP', 'Spain, Peseta', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000139, 5006, 'ETB', 'Ethiopia, Birr', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000140, 5006, 'EUR', 'European Economic and Monetary Union (EMU), Euro', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000141, 5006, 'FIM', 'Finland, Markka', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000142, 5006, 'FRF', 'France, Franc', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000143, 5006, 'GBP', 'Great Britain, Pound Sterling', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000144, 5006, 'GHC', 'Ghana, Cedi', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000145, 5006, 'GMD', 'Gambia, Dalasi', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000146, 5006, 'GRD', 'Greece, Drachma', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000147, 5006, 'HKD', 'Hong Kong, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000148, 5006, 'HUF', 'Hungary, Forint', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000149, 5006, 'IDR', 'Indonesia, Rupiah', 1, 0, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000150, 5006, 'IEP', 'Ireland (Eire), Punt', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000151, 5006, 'ILS', 'Israel, Shekel', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000152, 5006, 'INR', 'India, Rupee', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000153, 5006, 'IQD', 'Iraq, Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000154, 5006, 'IRR', 'Iran, Rial', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000155, 5006, 'ISK', 'Iceland, Krona', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000156, 5006, 'ITL', 'Italy, Lira', 1, 0, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000157, 5006, 'JMD', 'Jamaica, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000158, 5006, 'JOD', 'Jordan, Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000159, 5006, 'JPY', 'Japan, Yen', 1, 0, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000160, 5006, 'KES', 'Kenya, Shilling', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000161, 5006, 'KRW', 'Korea (South), Won', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000162, 5006, 'KWD', 'Kuwait, Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000163, 5006, 'LBP', 'Lebanon, Pound', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000164, 5006, 'LSM', 'Lesotho loti ', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000165, 5006, 'LVL', 'Latvia, Lat', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000166, 5006, 'MAD', 'Morocco, Dirham', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000167, 5006, 'MRO', 'Mauritania, Ouguiya', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000168, 5006, 'MTP', 'Malta, Maltese Pound', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000169, 5006, 'MUR', 'Mauritius, Rupee', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000170, 5006, 'MWK', 'Malawi, Kwacha', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000171, 5006, 'MXN', 'Mexico, Mexican Peso', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000172, 5006, 'MYR', 'Malaysia, Ringgit', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000173, 5006, 'MZM', 'Mozambique, Metical', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000174, 5006, 'NGN', 'Nigeria, Naira', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000175, 5006, 'NLG', 'Holland (The Netherlands), Guilder', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000176, 5006, 'NOK', 'Norway, Krone', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000177, 5006, 'NZD', 'New Zealand, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000178, 5006, 'OMR', 'Oman, Sul Rial', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000179, 5006, 'PEN', 'Peru, Nuevo Sol', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000180, 5006, 'PHP', 'Philippines, Peso', 1, 4, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000181, 5006, 'PKR', 'Pakistan, Rupee', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000182, 5006, 'PLN', 'Poland, Zloty', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000183, 5006, 'PTE', 'Portugal, Escudo', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000184, 5006, 'PYG', 'Paraguay, Guarani', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000185, 5006, 'QAR', 'Qatar, Rial', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000186, 5006, 'ROL', 'Romania, Leu', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000187, 5006, 'RUB', 'Russia, Ruble', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000188, 5006, 'RUR', 'Russia, Ruble', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000189, 5006, 'SAR', 'Saudi Arabia, Riyal', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000190, 5006, 'SCR', 'Seychelles, Rupee', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000191, 5006, 'SEK', 'Sweden, Krona', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000192, 5006, 'SGD', 'Singapore, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000193, 5006, 'SKK', 'Slovakia, Koruna', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000194, 5006, 'SLL', 'Sierra Leone, Leone', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000195, 5006, 'SYP', 'Syria, Pound', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000196, 5006, 'SZL', 'Swaziland, Lilangeni', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000197, 5006, 'THB', 'Thailand, Baht', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000198, 5006, 'TND', 'Tunisia, Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000199, 5006, 'TRL', 'Turkey, Lira', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000200, 5006, 'TWD', 'Taiwan, Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000201, 5006, 'TZS', 'Tanzania, Shilling', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000202, 5006, 'UGS', 'Uganda, Shilling', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000203, 5006, 'USD', 'United States of America, US Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'A');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000204, 5006, 'UYU', 'Uruguay, Peso', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000205, 5006, 'VEB', 'Venezuela, Bolivar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000206, 5006, 'VND', 'Viet Nam, Dong', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000207, 5006, 'XAF', 'Communaut? Financi?re Africaine (CFA), Franc', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000208, 5006, 'XAG', 'Silver, Ounces', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000209, 5006, 'XAU', 'Gold, Ounces', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000210, 5006, 'XPD', 'Palladium Ounces', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000211, 5006, 'XPT', 'Platinum, Ounces', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000212, 5006, 'YER', 'Yemen, Rial', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000213, 5006, 'YUM', 'Yugoslavia, New Dinar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000214, 5006, 'ZAR', 'South Africa, Rand', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000215, 5006, 'ZMK', 'Zambia, Kwacha', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000216, 5006, 'ZRN', 'Zaire, New Zaire', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000217, 5006, 'ZWD', 'Zimbabwe, Zimbabwe Dollar', 1, 2, NULL, NULL, 1000000, NULL, NULL, 'B');
INSERT INTO A_INSTRUMENT ( ID, TYPE, NAME, DESCR, CURRENCY, AMT_PLACES, EXPIRATION_DATE, SIGNATURE, STATE_ID, STATUS_TYPE, NDF, CLAZZ )
	VALUES (1000218, 5006, 'PHO', 'Philippines, Peso (OS)', 1, 4, NULL, NULL, 1000000, NULL, NULL, 'B');




DELETE ARCH_REPORT_COLUMN where id in (1100406,1100407);
INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE,
VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME ) VALUES (
1100406, 1100400, 'SIDE_A', 'TParty', 'TParty', 'String', 'string', NULL, NULL, NULL
, NULL, 70, 'SIDE_A');
INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE,
VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME ) VALUES (
1100407, 1100400, 'SIDE_B', 'CParty', 'CParty', 'String', 'string', NULL, NULL, NULL
, NULL, 80, 'SIDE_B');
INSERT INTO ARCH_REPORT_COLUMN (ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE,
VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME ) VALUES (
1100605, 1100400, 'TP_ROLE', 'TP Role', 'TP Role', 'String', 'string', NULL, NULL,
'reportHidden',	NULL, 590, 'TP_ROLE');

-- manual fix moving stf 12.1:2 to stf 12.1:3
insert into arch_code_member (group_id, code_key,data,name,status) values (1001000,4,'JPMC','JPMC',1);

begin
alter_constraints('enable');
end;
/