-----------------------------------------------------
--- Creation Date: 19-Apl-2004
--- Last Update : 19-Apl-2004
--- Aouthor : Nir Fuchs
--- Company : Traiana Inc
--- Script Target:
---	Update Database schema 1.7 STF 12.1 Build 5 to 1.7 STF 12.1 Build 7 on JPMC project
---	** Schema 1.7 STF 12.1 Build 5 is identical to schema 1.7 STF 12.1 Build 6
------------------------------------------------------

INSERT INTO ARCH_VERSION ( TIMESTAMP, VERSION, DESCRIPTION, LOGFILE, SOLUTION_VERSION )
	VALUES (sysdate , '1.7.12.1::7', 'jpmc 1.7 stf 12', '/Arch2.0/installationLog/databaseInstall.log', '1.7.12.1::7');

begin
alter_constraints('disable');
end;
/


-- Override Origin System Defs for Linear/Option Back-Office Systems
DELETE FROM ARCH_CODE_MEMBER WHERE group_id = 1001000 AND code_key IN ('2', '3');

INSERT INTO ARCH_CODE_MEMBER ( GROUP_ID, CODE_KEY, DATA, NAME, CODE_COMMENT, STATUS ) VALUES ( 
1001000, '2', 'IRFE', 'IRFE', 'Origin System IRFE', 1); 
INSERT INTO ARCH_CODE_MEMBER ( GROUP_ID, CODE_KEY, DATA, NAME, CODE_COMMENT, STATUS ) VALUES ( 
1001000, '3', 'Murex', 'Murex', 'Origin System Murex', 1);


delete from ARCH_REPORT_COLUMN where id>=1100800 and id<=1100829;

-- ARCH_REPORT_COLUMN
INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100800, 1100800, 'TRAIANA_ID', 'Traiana Trade ID', 'Traiana Trade ID', 'Long', 'long', NULL, NULL, NULL, 'reportnosort;LINK:javascript:traianaTradeIdRef($TRAIANA_ID)', 10, 'TRAIANA_ID');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100801, 1100800, 'EXPIRY_DATE', 'Expiry Date', 'Expiry Date', 'Date', 'todayOrSysdate', NULL, NULL, NULL, 'reportnosort', 20, 'trunc(EXPIRY_DATE)');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100802, 1100800, 'FUND', 'Fund', 'Fund', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 30, 'FUND');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100803, 1100800, 'COUNTERPARTY', 'Counterparty', 'Counterparty', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 40, 'COUNTERPARTY');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100804, 1100800, 'OPTION_TYPE', 'Option Type', 'Option Type', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 50, 'OPTION_TYPE');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100805, 1100800, 'DIRECTION', 'Buy/Sell', 'Buy/Sell', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 60, 'DIRECTION');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100806, 1100800, 'CONTRACT_TYPE', 'Call/Put', 'Call/Put', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 70, 'CONTRACT_TYPE');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100807, 1100800, 'RISK_CCY', 'Risk Ccy', 'Risk Ccy', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 80, 'RISK_CCY');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100808, 1100800, 'RISK_NOTIONAL', 'Risk Notional', 'Risk Notional', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;ccy', 90, 'RISK_NOTIONAL');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100809, 1100800, 'BASE_CCY', 'Base Ccy', 'Base Ccy', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 100, 'BASE_CCY');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100810, 1100800, 'BASE_NOTIONAL', 'Base Notional', 'Base Notional', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;ccy', 110, 'BASE_NOTIONAL');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100811, 1100800, 'STRIKE', 'Strike', 'Strike', 'Double', 'double', NULL, NULL, NULL, 'reportnosort', 120, 'STRIKE');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100812, 1100800, 'PRICE', 'Price', 'Price', 'Double', 'double', NULL, NULL, NULL, 'reportnosort', 130, 'PRICE');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100813, 1100800, 'PRICE_NOTIONAL', 'Price Quote Mode', 'Price Quote Mode', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 140, 'PRICE_NOTIONAL');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100814, 1100800, 'VOLATILITY', 'Vol', 'Vol', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_spot8', 150, 'VOLATILITY');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100815, 1100800, 'SPOT', 'Spot', 'Spot', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_spot8', 160, 'SPOT');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100816, 1100800, 'DELTA_CCY', 'Delta Ccy', 'Delta Ccy', 'String', 'string', NULL, NULL, NULL, 'reportnosort;m', 170, 'DELTA_CCY');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100817, 1100800, 'DELTA', 'Delta', 'Delta', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_spot8', 180, 'DELTA');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100818, 1100800, 'GAMMA', 'Gamma', 'Gamma', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_spot8', 190, 'GAMMA');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100819, 1100800, 'VEGA', 'Vega', 'Vega', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_spot8', 200, 'VEGA');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100820, 1100800, 'D_DELTA', '$ Delta', '$ Delta', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_ccy', 210, 'D_DELTA');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100821, 1100800, 'D_GAMMA', '$ Gamma', '$ Gamma', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_ccy', 220, 'D_GAMMA');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100822, 1100800, 'D_VEGA', '$ Vega', '$ Vega', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_ccy', 230, 'D_VEGA');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100823, 1100800, 'TOTAL_DAILY_PNL', '$ Daily PnL', '$ Daily PnL', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_ccy', 240, 'TOTAL_DAILY_PNL');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100824, 1100800, 'TOTAL_MTD_PNL', '$ MTD PnL', '$ MTD PnL', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_ccy', 250, 'TOTAL_MTD_PNL');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100825, 1100800, 'TOTAL_MTM_PNL', '$ MTM', '$ MTM', 'Double', 'double', NULL, NULL, NULL, 'reportnosort;m_ccy', 260, 'TOTAL_MTM_PNL');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100826, 1100800, 'TRADER', 'Trader', 'Trader', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 270, 'TRADER');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100827, 1100800, 'PORTFOLIO', 'Portfolio', 'Portfolio', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 280, 'PORTFOLIO');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100828, 1100800, 'AGREEMENT', 'Agreement', 'Agreement', 'String', 'string', NULL, NULL, NULL, 'reportnosort', 290, 'AGREEMENT');

INSERT INTO ARCH_REPORT_COLUMN ( ID, REPORT_ID, LOGICAL_NAME, VISIBLE_NAME, FILTER_NAME, TYPE, VALIDATOR, CONVERTER, HELPER, VISIBILITY, SETTER, ORDER_SEQ, TABLE_NAME )
    VALUES ( 1100829, 1100800, 'FAKE_ROW', 'FAKE_ROW', 'FAKE_ROW', 'Long', 'long', NULL, NULL, 'none', '', 300, 'FAKE_ROW');


begin
alter_constraints('enable');
end;
/
