DROP TABLE TEMP_MONITORING;

CREATE TABLE TEMP_MONITORING(TP_ID, ORIG_INTER_VAL, TOP_WAIT,  PRIMARY KEY (TP_ID, ORIG_INTER_VAL, TOP_WAIT)) ORGANIZATION INDEX AS
SELECT TP_ID, ORIG_INTER_VAL, TOP_WAIT FROM FEED_STATISTICS;