delete A_POSITION_SEMI_AGG_INSTR_2_TA;
 delete  A_POSITION_SEMI_AGG_INSTR_ALL;
 delete  A_POSITION_SEMI_AGG_TRADE_2_TA;
 delete  A_POSITION_SEMI_AGG_TRADE_ALL;
 delete A_POSITION_SEMI_AGG_INSTR;
 delete  A_POSITION_SEMI_AGG_TRADE;
 delete   A_POSITION_SEMI_AG_TR_2_TA_HIS;
 delete  A_POSITION_SEMI_AG_TR_ALL_HIS;
 delete M_FX_NOE_2_POS_COMBINATION;
 delete M_FX_NOE;
 delete M_FX_OPTION_NOE;
 delete M_FX_TRADE;
 delete M_FX_OA_ALLOCATION;
 delete M_FX_OA;
 delete A_OA_ALLOCATION;
 delete A_OA;
 delete A_TA;
 delete A_CREDIT_RESULTS;
 delete A_CREDIT_MULTI_RESULTS;
 delete A_CREDIT_RESULTS_HISTORY ;
  delete A_CREDIT_MULTI_RESULTS_HIS ;
  delete A_GENERIC_NOE_DEALS;
    delete A_GENERIC_OA_DEALS;
	  delete A_GENERIC_REQUEST_DEALS;
  
  commit;
 